name: Deploy to Firebase Hosting on Push
#'on': push
#on: workflow_dispatch
'on': 
 workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
jobs:
    deploy:
     runs-on: ubuntu-latest
     
     environment:
      name: development
      url: https://gitapprovalgates-dev.web.app
      
     steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        run: npm install    
      - name: Build App
        run: npm run build          
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
