name: Move to Firebase storage on Push
#'on': push
#on: workflow_dispatch
'on': 
 workflow_dispatch:
    inputs:
      environment:
        description: 'Environment(Dev/Stg)'
        required: true
        default: 'dev'         
 jobs:
  job_id:
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        # credentials_json: '${{ secrets.FIREBASE_TOKEN }}'     
  
- id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: '/public'
        destination: 'gs://gitapprovalgates-dev.appspot.com'
