name: Move to Firebase storage on Push
#'on': push
#on: workflow_dispatch
'on': 
 workflow_dispatch:
    inputs:
      environment:
        description: 'Environment(Dev/Stg)'
        required: true
        default: 'dev'   
        
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      
      - name: Install Packages
        run: npm install  
      
      - name: Build App
        run: npm run build 
        
      - name: Upload the build output
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            output/
            .firebaserc
            firebase.json
          retention-days: 1
          
  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download the build output
        uses: actions/download-artifact@v2
        with:
          name: build
          
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.GCP_CRED }}"
          channelId: live
          projectId: gitapprovalgates-dev 
          
# jobs:
#   job_id:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: 'read'
#       id-token: 'write'  
      
#     steps:
#     - uses: 'actions/checkout@v2'
#     - name: Install Packages
#       run: npm install  
      
#     - name: Build App
#       run: npm run build 
      
# #     - name: Upload Artifact
# #       uses: actions/upload-artifact@master
# #       with:
# #          name: build
# #          path: build
           
# #     - id: 'auth'
# #       uses: 'google-github-actions/auth@v0'
# #       with:
# #            credentials_json: '${{ secrets.GCP_CRED }}'
  
# #     - id: 'upload-folder'
# #       uses: 'google-github-actions/upload-cloud-storage@v0'
# #       with:
# #           path: './public'
# #           destination: 'gitapprovalgates-dev.appspot.com'
# #           parent: false
          
          
