name: Move to Firebase storage on Push
#'on': push
#on: workflow_dispatch
'on': 
 workflow_dispatch:
    inputs:
      environment:
        description: 'Environment(Dev/Stg)'
        required: true
        default: 'dev'         
jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'  
      
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
           credentials_json: '${{ secrets.GCP_CRED }}'
  
    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
          path: 'Jan25'
          destination: 'gitapprovalgates-dev.appspot.com'
          parent: false
