name: Move to Firebase storage on Push
#'on': push
#on: workflow_dispatch
'on': 
 workflow_dispatch:
    inputs:
      environment:
        description: 'Environment(Dev/Stg)'
        required: true
        default: 'dev'   
        
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      
      - name: Install Packages
        run: npm install  
      
      - name: Build App
        run: npm run build 
        
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
          
  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download the build output
        uses: actions/download-artifact@v2
        with:
          name: build
          
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
           credentials_json: '${{ secrets.GCP_CRED }}'
  
      - name: Delete files from bucket
        run: gsutil rm gs://gitapprovalgates-dev.appspot.com/**

#       - id: 'upload-folder'
#         uses: 'google-github-actions/upload-cloud-storage@v0'
#         with:
#           path: '.'
#           destination: 'gitapprovalgates-dev.appspot.com'   
      
          
# jobs:
#   job_id:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: 'read'
#       id-token: 'write'  
      
#     steps:
#     - uses: 'actions/checkout@v2'
#     - name: Install Packages
#       run: npm install  
      
#     - name: Build App
#       run: npm run build 
      
# #     - name: Upload Artifact
# #       uses: actions/upload-artifact@master
# #       with:
# #          name: build
# #          path: build
           
# #     - id: 'auth'
# #       uses: 'google-github-actions/auth@v0'
# #       with:
# #            credentials_json: '${{ secrets.GCP_CRED }}'
  
# #     - id: 'upload-folder'
# #       uses: 'google-github-actions/upload-cloud-storage@v0'
# #       with:
# #           path: './public'
# #           destination: 'gitapprovalgates-dev.appspot.com'
# #           parent: false
          
          
